# Generated by Django 3.2.15 on 2022-10-13 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.payments'),
        ),
        migrations.AddField(
            model_name='orders',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='properties.properties'),
        ),
        migrations.AddField(
            model_name='orders',
            name='wallet_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_out', to='payments.wallet'),
        ),
        migrations.AddField(
            model_name='orders',
            name='wallet_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_in', to='payments.wallet'),
        ),
    ]
