# Generated by Django 3.2.15 on 2022-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='safe_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Safe amount'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Complete'), (2, 'Cancelled')], default=0, verbose_name='Status'),
        ),
    ]
