# Generated by Django 3.2.16 on 2022-10-31 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_cancelmultiplier_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelmultiplier',
            name='amount_0',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Amount last 24h'),
        ),
        migrations.AlterField(
            model_name='cancelmultiplier',
            name='amount_168',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Amount 168h+'),
        ),
        migrations.AlterField(
            model_name='cancelmultiplier',
            name='amount_24',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Amount 72h-24h'),
        ),
        migrations.AlterField(
            model_name='cancelmultiplier',
            name='amount_72',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Amount 168h-72h'),
        ),
    ]
