# Generated by Django 3.2.16 on 2022-11-03 07:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_properties_views'),
        ('payments', '0009_auto_20221031_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.SmallIntegerField(choices=[(0, 'New'), (1, 'Popular'), (2, 'Top')], default=0, verbose_name='Badge')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PromotionObjects', to='payments.promotion')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PromotionObjects', to='properties.properties')),
            ],
        ),
    ]
