# Generated by Django 3.2.16 on 2022-10-27 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 13, 17, 21, 690552, tzinfo=utc), null=True),
        ),
    ]
