# Generated by Django 3.2.15 on 2022-10-13 12:38

import core.file_storage
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.file_storage.dynamic_image_file_path, validators=[core.validators.validate_images_file_max_size], verbose_name='Linked image')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'properties'), ('model', 'properties')), models.Q(('app_label', 'social'), ('model', 'review')), models.Q(('app_label', 'social'), ('model', 'report')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
