# Generated by Django 3.2.16 on 2022-11-01 14:01

import core.file_storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_linkedimages_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedimages',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.file_storage.dynamic_image_file_path, validators=[core.validators.validate_images_file_max_size], verbose_name='Linked image thumbnail'),
        ),
    ]
