# Generated by Django 3.2.16 on 2022-11-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_linkedimages_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedimages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
