# Generated by Django 3.2.15 on 2022-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='safety_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Safety deposit'),
        ),
    ]
