# Generated by Django 3.2.16 on 2022-10-18 13:51
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_properties_safety_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(16, 00), verbose_name='Arrival time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='departure_time',
            field=models.TimeField(default=datetime.time(16, 00), verbose_name='Departure time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='additional_rules',
            field=models.TextField(blank=True, null=True, verbose_name='Additional rules'),
        ),
    ]
