# Generated by Django 3.2.16 on 2022-10-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rename_tittle_properties_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitiesbinding',
            name='custom_amenity',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Custom amenity'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='flat_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Atelier'), (1, 'Apartment'), (2, 'Loft')], null=True, verbose_name='Flat type'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='hotel_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Hotel'), (1, 'Hostel'), (2, 'Resort'), (3, 'B&B'), (4, 'Apart-hotel')], null=True, verbose_name='Hotel type'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='house_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'House'), (1, 'Country house'), (2, 'Cottage'), (3, 'Townhouse')], null=True, verbose_name='House type'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='room_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Room with amenities'), (1, 'Room in apartment'), (2, 'Bed in common room')], null=True, verbose_name='Room type'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='unique_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Transport'), (1, 'Natural'), (2, 'Tower'), (3, 'Other')], null=True, verbose_name='Unique type'),
        ),
    ]
