# Generated by Django 3.2.16 on 2022-10-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_properties_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
    ]
