# Generated by Django 3.2.16 on 2022-10-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_properties_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='tittle',
        ),
        migrations.AddField(
            model_name='amenities',
            name='title',
            field=models.CharField(null=True, blank=True, default=None, max_length=250, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
    ]
