# Generated by Django 3.2.16 on 2022-11-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20221028_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
