version: "3.9"

networks:
  proxy_prod: # docker network create --driver=overlay --internal=false --attachable proxy_prod
    driver: overlay
    attachable: true
    internal: false
    name: proxy_prod

services:
  rabbit:
    image: rabbitmq:3.8.26-management
    container_name: server-rabbit
    networks:
      - proxy_prod
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5672:5672'
      # - '15672:15672'
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy_prod
        # - traefik.http.routers.rabbitmq.entrypoints=websecure
        # - traefik.http.routers.rabbitmq.rule=Host(`${RABBIT_DOMAIN}`)
        - traefik.http.routers.rabbitmq.tls=true
        - traefik.http.routers.rabbitmq.tls.certresolver=letsencrypt
        - traefik.http.routers.rabbitmq.service=rabbitmq_service
        - traefik.http.services.rabbitmq_service.loadbalancer.server.port=5672
