# Generated by Django 3.2.15 on 2022-10-13 12:38

import core.file_storage
import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(1, 'New user greeting'), (2, 'Property created. Awaiting approval'), (3, 'Property status changed'), (4, 'New review in your property'), (5, 'Property paid'), (6, 'Arrival time is ending'), (7, 'Withdraw request placed'), (8, 'Withdraw request complete'), (9, 'Property viewed'), (10, 'Property discount')], verbose_name='code')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Is viewed')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.file_storage.review_image_file_path, validators=[core.validators.validate_images_file_max_size], verbose_name='Review image')),
                ('tittle', models.CharField(max_length=200, verbose_name='Tittle')),
                ('description', models.TextField(verbose_name='Description')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'properties'), ('model', 'properties')), models.Q(('app_label', 'users'), ('model', 'user')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='review', to='contenttypes.contenttype')),
            ],
        ),
    ]
