# Generated by Django 3.2.16 on 2022-10-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.SmallIntegerField(choices=[(0, 'The ad is not relevant'), (1, 'Incorrect data'), (2, 'Misleading price or terms'), (3, 'This is not real housing'), (4, 'This is a scam'), (5, 'Contains offensive materials'), (6, 'Other')], default=0, verbose_name='Report type'),
            preserve_default=False,
        ),
    ]
