# Generated by Django 3.2.16 on 2022-10-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20221024_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-10-20T15:09:52.550Z', verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
