# Generated by Django 3.2.16 on 2022-10-27 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20221026_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 13, 17, 21, 708006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 13, 17, 21, 707006, tzinfo=utc), verbose_name='Created at'),
        ),
    ]
