# Generated by Django 3.2.16 on 2022-10-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20221027_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportList',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('social.report',),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'New'), (1, 'In progress'), (2, 'Resolved'), (3, 'Rejected')], default=0, verbose_name='Status'),
        ),
    ]
