# Generated by Django 3.2.16 on 2022-10-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20221027_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tittle',
            new_name='title',
        ),
    ]
