# Generated by Django 3.2.16 on 2022-11-15 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0013_alter_favorite_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New user greeting'), (2, 'Property created. Awaiting approval'), (3, 'Property status changed'), (4, 'New review in your property'), (5, 'Property paid'), (6, 'Arrival time is ending'), (7, 'Withdraw request placed'), (8, 'Withdraw request complete'), (9, 'Property viewed'), (10, 'Property discount'), (11, 'Report resolved'), (12, 'Report rejected')], verbose_name='code'),
        ),
        migrations.CreateModel(
            name='ReportMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReportMessages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
